name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  API_KEY: ""
  OPENAI_API_BASE_URL: ""
  DEFAULT_MODEL_ID: ""

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run rustfmt
      run: cargo fmt --check
    - name: Run clippy
      run: cargo clippy --all-features --all-targets -- -D clippy::all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit testing
        run: cargo test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose